// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkrHxtomQxJJ9R7DCIyx6kUE8Yk0UbNs0',
    appId: '1:840436675517:web:c24827fba2955b742858d4',
    messagingSenderId: '840436675517',
    projectId: 'diwali-rnd-90ab3',
    authDomain: 'diwali-rnd-90ab3.firebaseapp.com',
    storageBucket: 'diwali-rnd-90ab3.appspot.com',
    measurementId: 'G-XTEHV1RHJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf9My88rQszY8EFHMGUH-yNoPQmPSSrx8',
    appId: '1:840436675517:android:5bd92de28871a0d42858d4',
    messagingSenderId: '840436675517',
    projectId: 'diwali-rnd-90ab3',
    storageBucket: 'diwali-rnd-90ab3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoA0lrEmFMEK6Gufnr5pwgTv6XiAgd4uQ',
    appId: '1:840436675517:ios:b60cb46ce544d1f22858d4',
    messagingSenderId: '840436675517',
    projectId: 'diwali-rnd-90ab3',
    storageBucket: 'diwali-rnd-90ab3.appspot.com',
    iosBundleId: 'com.example.diwaliRnd',
  );
}
